# Generated by Django 3.1.2 on 2020-10-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20)),
                ('header', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=30)),
            ],
        ),
    ]
