# Generated by Django 3.1.2 on 2020-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='status',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
