# Generated by Django 3.1.2 on 2020-10-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_newslist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslist',
            name='status',
        ),
    ]
