# Generated by Django 3.1.2 on 2020-10-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_newslist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='whiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20)),
            ],
        ),
    ]
